- name: Transfer and execute a script.
  hosts: all
  gather_facts: true
  tasks:

     - name: Execute the script to check ldap
       script:  sh /opt/vox/bin/check_services.sh
       register: out
